### ISSUE TITLE
This line cannot build

### ISSUE THREAD

**Issue by asmyasnikov** [consbio/mbtileserver#101]
https://github.com/consbio/mbtileserver/blob/2af50e0314759782b6f7cb01f752fd4fbaa84d1f/handlers/serviceset.go#L144

**Comment by brendan-ward** [comment]
Good catch!  Apparently `log.Writer()` was not defined on Go < = 1.12, possibly because we didn't initialize it with a writer ourselves.

This is fixed now in d8a4f6c221e81063ef540906d0caa51ec01ab291
