### ISSUE TITLE
caching options

### ISSUE THREAD

**Issue by xinyuluo** [consbio/mbtileserver#141]
Thanks for the awesome project! I'm new to this tool, and this is more like a question than an issue. I learned from README that it's possible to add cache control headers. I wonder how caching is done in mbtileserver: what's being cached (response or the tile data), and is there a max limit for the cache?

Thank you 🙏

**Comment by brendan-ward** [comment]
@xinyuluo thanks for the question.

The cache control headers control caching on the client (browser) side, those do not correspond to caching on the server.

At present we have no caching on the server.  In the earliest versions of this tool, we had in-memory caching for the most frequently used tiles, but that added unnecessary complexity and we removed it early on.  At present, the mbtiles files are effectively one of the best cases for on-disk caches anyway, so there isn't (in my opinion, not validated by testing) much benefit to having a secondary on-disk cache.

Depending on your use case and your server capacity, there may be some benefit to having an in-memory cache for most frequently requested tiles, but you should implement that yourself along with a reverse proxy; it is out of scope for `mbtileserver`.  Our focus is to make this run on servers with tiny amounts of memory, so I don't want to build in an in-memory cache by default.
