### ISSUE TITLE
it is not support EPSG 4326

### ISSUE THREAD

**Issue by Lemonjay** [consbio/mbtileserver#163]
Is any way to support the 4326 coordinates

**Comment by brendan-ward** [comment]
@Lemonjay your question / issue is not at all clear.  Can you please clarify specifically what you are asking for here?

`mbtileserver` simply serves tiles that are created in advance using some other tool.  For instance, `tippecanoe` converts from GeoJSON in EPSG:4326 coordinates to spherical Mercator coordinates, which are the standard for mbtiles files.  `mbtileserver` does not process tiles.  So - if you want to support EPSG 4326 coordinates within your tiles - which does not follow the mbtiles standard, you have to create your tiles in that coordinate system but trick your tiling engine into thinking that they are in spherical Mercator coordinates like in [this example](https://blog.mapbox.com/mapping-arctic-sea-ice-in-a-polar-projection-a8fd68a03c53).  However, that means that you won't be able to leverage existing basemaps.

**Comment by brendan-ward** [comment]
Nothing actionable here, closing
