### ISSUE TITLE
fun with logrus dependency lowercased name change

### ISSUE THREAD

**Issue by schorsch** [consbio/mbtileserver#29]
the logrus repo was renamed from github.com/Sirupsen/logrus to lowercased github.com/sirupsen/logrus so go build does not work for me anymore because logrus_sentry has changed it already .. what a hickup i can tell you. 

After renaming the imports to lowercase in main.go and mbtileserver it compiles. 

Is there any chance that you can tackle this issue?

**Comment by brendan-ward** [comment]
@schorsch I've resolved this (and other dependency update issues) in the `update-deps` branch.

Note: that is based off the `utfgrid` branch, which is still in review, and involved fairly significant refactoring of the internals.

I'm hoping to get both merged into `master` in the next couple of days.

**Comment by brendan-ward** [comment]
resolved by 5a0ee8090f8a9023d71b6be8b923c73121c0dd11

**Comment by schorsch** [comment]
Thanks!
