### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by brianvoe** [consbio/mbtileserver#33]
I want to first of all say that I am extremely happy that someone has put this together and want to say what a great job you have done with this.

Upon using this there is one thing that has come up which is if there is not a tile for something(which is completely normal) but console logs an error of 404 not found. Upon trying to see if i could get mapbox gl to suppress it I came to find out that its not so much a mapbox issue as it is the server returning 404. They recommended having the server send back 204, which is a successful request with no content.

Let me know your thoughts.

Thanks

**Comment by brendan-ward** [comment]
@brianvoe Good suggestion, I'll give it a try.  I wasn't sure how to handle missing vector tiles.  For image tiles, we send back a transparent image.

**Comment by brianvoe** [comment]
Sounds good!

**Comment by brianvoe** [comment]
Let me know when you get a chance to update this. We were looking to get this into production soon. Thanks!

**Comment by brendan-ward** [comment]
@brianvoe see the `issue33` branch; I pushed changes last night.  Let me know if that resolves the issue for you.

Unfortunately I was working on a machine that has very poor capabilities for WebGL, and couldn't even open the mapbox GL maps to test the solution.  I'll try to test on a different machine today and merge to `master`.

**Comment by brianvoe** [comment]
Ya everything looks good to me.

**Comment by brendan-ward** [comment]
Resolved via d43d10ca6de773e7128f686ff117a1eb687b50f1
