### ISSUE TITLE
Does it support combining MBTiles?

### ISSUE THREAD

**Issue by Xeenych** [consbio/mbtileserver#62]
I have several MBTiles and I wnat the server to combine them on-the-fly. Is it possible?

**Comment by brendan-ward** [comment]
@Xeenych Sorry, no this is not something that `mbtileserver` currently provides.

We use [`tippecanoe`](https://github.com/mapbox/tippecanoe) `tile-join` to combine multiple tilesets into a single mbtiles file prior to serving with `mbtileserver`.

Can you tell us more about your use case for needing to merge tilesets on the fly?  What type of data are you working with?  Why do they need to be merged on the fly instead of in advance?

**Comment by brendan-ward** [comment]
Is each sheet a different dataset or combination of datasets?  Or is it a specific geographic area?

Am I correct in seeing that your tiles are all image (PNG) tiles, and not vector tiles?  While vector tiles  have a straightforward path for merging multiple tilesets into a single tileset, I have not seen anything similar for raster tiles.

This looks like an interesting project, but I think merging on the fly is more complexity than we want to introduce to `mbtileserver` - so my recommendation is to work with tools that merge mbtiles files in advance.  It might be more performant todo this from the mbtiles files from each sheet than trying to merge sheets together in QGIS.  QGIS Sheet => mbtiles per sheet => merge => single mbtiles file for serving.

There are a variety of mbtiles libraries out there in your language of choice.  We have one that we've used a bit in various projects: [pymbtiles](https://github.com/consbio/pymbtiles).  One could use that for managing the IO to / from mbtiles files, and use Python to build a function for merging the raster images.

**Comment by Xeenych** [comment]
Each sheet corresponds to printed map sheet in a specific grid.
If I merge 200 sheets this will take whole day on my personal computer and will take a lot of space. Then I will need to upload this merged file to an ftp.
And when I need to change some detail in one sheet I will need to rebuild and merge all sheet again and upload it and so on.
I tried TileMill and GlobalMapper. They cannot handle such amount of raster data for a reasonable time.

Look like tilestache can merge mbtiles on-the-fly and other sources.
