### ISSUE TITLE
can not display map, download the mbtiles from openmaptiles.

### ISSUE THREAD

**Issue by higoalespn** [consbio/mbtileserver#63]
Hello, I download mbtiles file from openmaptiles, use the command as follow:
mbmatch -debug true -path 2017-07-03_us_new-york.mbtiles.
but when I open the http://localhost:7000/, I can't see anything on browser.

**Comment by brendan-ward** [comment]
@higoalespn we've been able to use `mbtileserver` for tiles downloaded from openmaptiles without issue, using the latest version of `mbtileserver`.

There isn't enough information here to help me troubleshoot.  What command did you use to start `mbtileserver`?

Also note that there is nothing on the root URL, you must go to `http://<host>:<port>/services` endpoint to see a listing of services.  See [this](https://github.com/consbio/mbtileserver#examples) for more information.

**Comment by brendan-ward** [comment]
stale issue, closing
