### ISSUE TITLE
Drop Leaflet, move everything to Mapbox GL

### ISSUE THREAD

**Issue by brendan-ward** [consbio/mbtileserver#65]
This is nothing against Leaflet, which remains as awesome as ever.

However, for easier maintenance and enhancements, it would be best to limit our map preview technology to a single type.

**Comment by brendan-ward** [comment]
Upgrade of Mapbox GL beyond 0.33.x will require using a different JSON fetch handler; the one we are using here has been [removed](https://github.com/mapbox/mapbox-gl-js/issues/4393).

**Comment by brendan-ward** [comment]
When we do this, we likely need to bring in `babel` and support at least some polyfills.

However, instead of other bundlers, we might be able to leverage (esbuild)[https://github.com/evanw/esbuild].

**Comment by slachiewicz** [comment]
maybe https://github.com/maplibre/maplibre-gl-js ?

**Comment by brendan-ward** [comment]
maplibre-gl-js is certainly an option and avoids some of the issues around Mapbox tokens once mapbox-gl-js 1.13 is no longer being maintained and only upgrade path there is 2+.

Another alternative would be OpenLayers like [mbtileserver-rs](https://github.com/maplibre/mbtileserver-rs)
