### ISSUE TITLE
Gracefully handle missing tile service bounds in map preview

### ISSUE THREAD

**Issue by brendan-ward** [consbio/mbtileserver#83]
The [mbtiles spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md#content) suggests but does not require `bounds` to be defined for the tile service.

The preview pages assume that bounds are defined, and fail poorly when it is missing.

**Comment by sikmir** [comment]
Here is a workaround:
```sh
$ sqlite3 test.mbtiles "INSERT INTO metadata VALUES('bounds','-180,-85,180,85');"
```
