### ISSUE TITLE
Detect webp format

### ISSUE THREAD

**Issue by ka7eh** [consbio/mbtileserver#98]
When looking at the [specs for webp format](https://developers.google.com/speed/webp/docs/riff_container#webp_file_header), I noticed the bytes at positions 4-7 are the length of the file, which means the following line in `detectTileFormat` can fail:
https://github.com/consbio/mbtileserver/blob/7e953bac4f9123015a5cf3dc4c2f1fdceacc7ce6/mbtiles/mbtiles.go#L367

It can be fixed by checking against bytes at positions 0-4 and 8-11, which should be `RIFF` and `WEBP` respectively. You can see the python example here: https://github.com/python/cpython/blob/3.8/Lib/imghdr.py#L116

**Comment by brendan-ward** [comment]
Thanks @ka7eh and sorry for the very long delay in getting to this.  See #110
